on: [push]

env:
  RENV_PATHS_ROOT: ~/.local/share/renv


name: run-a-simple-script

jobs:
  run-a-simple-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install renv, if necessary
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")

      - name: Restore packages
        shell: Rscript {0}
        run: |
          renv::restore()

      - name: Run script
        run: |
          Rscript dt.R

      - name: View renv library
        run: |
          ls -l ${{ env.RENV_PATHS_ROOT }}/cache/*/*/*
